### ISSUE TITLE
Update LICENSE to account for changes from hammerjs/hammer.js

### ISSUE THREAD

**Issue by We-St** [naver/hammer.js#19]
Hi,

it seems the LICENSE for this project is still the same as the one here: https://github.com/hammerjs/hammer.js/blob/master/LICENSE.md

Can you please update this to reflect the work done in this repo?.

Thank you, S.

**Comment by WoodNeck** [comment]
Hello, @We-St. We've made a PR updating our license (#20)
Thanks for checking :)

**Comment by WoodNeck** [comment]
PR(#20) is now merged, thanks!
